### PR TITLE
Fix --installed, --maxsize, and --toolchains flags

### LINKED ISSUE #54: Installed, maxsize, and toolchains flags can't be used
When running `cargo sweep -i`:
```
thread 'main' panicked at '--time argument missing', /home/lynne/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-sweep-0.6.1/src/main.rs:232:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When running `cargo sweep -i -t 30`:
```
error: The argument '--installed' cannot be used with one or more of the other specified arguments

USAGE:
    cargo-sweep sweep <--stamp|--file|--time <days>|--installed|--toolchains <toolchains>|--maxsize <maxsize>>

For more information try --help
```

It seems as though the issue is that the time argument is `expect()`ed here:
https://github.com/holmgr/cargo-sweep/blob/932a08a184809144379ced4c833a28464df8b88b/src/main.rs#L226-L236

...even though the `--installed` flag never uses the value of `keep_duration` (and therefore it shouldn't be `expect()`ed):
https://github.com/holmgr/cargo-sweep/blob/932a08a184809144379ced4c833a28464df8b88b/src/main.rs#L253-L265

This issue also occurs with the `--toolchains` flag and `--maxsize` flags.

### PR DESCRIPTION
**Pull request by Lynnesbian**
This resolves #54:

```
$ cargo run -- sweep -i
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/cargo-sweep sweep -i`
[INFO] Using all installed toolchains: ["stable-x86_64-unknown-linux-gnu", "beta-x86_64-unknown-linux-gnu", "nightly-2020-10-25-x86_64-unknown-linux-gnu", "nightly-x86_64-unknown-linux-gnu", "1.42.0-x86_64-unknown-linux-gnu", "1.43.0-x86_64-unknown-linux-gnu"]
[INFO] Cleaned 0.00 bytes
```

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -286,18 +271,28 @@ fn main() {
...
-                Ok(cleaned_amount) => info!("Cleaned {}", format_bytes(cleaned_amount)),
-                Err(e) => error!("Failed to clean {:?}: {}", project_path, e),
+        } else {
+            let keep_duration = if matches.is_present("file") {
+                let ts = Timestamp::load(path.as_path()).expect("Failed to load timestamp file");
+                Duration::from(ts)
+            } else {
+                let days_to_keep: u64 = matches
+                  .value_of("time")
+                  .expect("--time argument missing")
```
Comment (Lynnesbian) [inline src/main.rs:281]: As far as I can tell, the `expect("--time argument missing")` can be replaced with an `unwrap()`, as `matches.value_of("time")` should always be set at this point in execution. I left it in because it doesn't really do any harm being there, and I could be wrong about it being unreachable.

**Comment by holmgr** [comment]
Looks good, thanks!

**Comment by phil-opp** [comment]
@holmgr Could you create a new crates.io release with this fix please?
